import bike1 from "../assets/bike1.jpg"
import bike2 from "../assets/bike2.jpg"
import bike3 from "../assets/bike3.jpg"
import bike4 from "../assets/bike4.jpg"
import bike5 from "../assets/bike5.jpg"
import bike6 from "../assets/bike6.jpg"
import bike7 from "../assets/bike7.jpg"
import bike8 from "../assets/bike8.jpg"
import bike9 from "../assets/bike9.jpg"
import bike10 from "../assets/bike10.jpg"
import bike11 from "../assets/bike11.jpg"
import bike12 from "../assets/bike12.jpg"
import bike13 from "../assets/bike13.jpg"
import bike14 from "../assets/bike14.jpg"
import bike15 from "../assets/bike215.jpg"
 export const trending=[
  { imgprodect: bike1 },
  { imgprodect: bike2 },
  { imgprodect: bike3 },
  { imgprodect: bike4 },
  { imgprodect: bike5 },
  { imgprodect: bike6 },
  { imgprodect: bike7 },
  { imgprodect: bike8 },
  { imgprodect: bike9 },
  { imgprodect: bike11 },
  { imgprodect: bike12 },
  { imgprodect: bike13 },
  { imgprodect: bike15 },
  { imgprodect: bike14 },
  { imgprodect: bike10 },
]